"""Remove admin2.

Revision ID: 1030718871ea
Revises: 5659d2671cc8
Create Date: 2015-09-27 21:12:48.554916

"""

# revision identifiers, used by Alembic.
revision = '1030718871ea'
down_revision = '5659d2671cc8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute(u'COMMIT;')
    op.execute(u'ALTER TYPE users_group ADD VALUE IF NOT EXISTS \'admin\';')
    op.execute(u'UPDATE users SET "group"=\'admin\' WHERE "group" in (\'admin1\', \'admin2\');')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
