"""Add AdminLogEntry class.

Revision ID: 13bb58c7ab9b
Revises: eddcb45d12
Create Date: 2015-05-28 21:55:41.147005

"""

# revision identifiers, used by Alembic.
revision = '13bb58c7ab9b'
down_revision = 'eddcb45d12'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('action_user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Unicode(length=50), nullable=False),
    sa.Column('description', sa.UnicodeText, nullable=True),
    sa.Column('affected_user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['affected_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_log_entries')
    ### end Alembic commands ###
