"""save character id in chats

Revision ID: 145af6928bec
Revises: 2075274e8da8
Create Date: 2016-03-26 03:13:35.696091

"""

# revision identifiers, used by Alembic.
revision = '145af6928bec'
down_revision = '2075274e8da8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_users', sa.Column('search_character_id', sa.Integer(), nullable=False, server_default='1'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_users', 'search_character_id')
    ### end Alembic commands ###
