"""empty message

Revision ID: 1678892f1bd4
Revises: ea30a8851312
Create Date: 2017-01-31 22:26:32.465920

"""

# revision identifiers, used by Alembic.
revision = '1678892f1bd4'
down_revision = 'ea30a8851312'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from newparp.model import Fandom


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fandoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(Fandom.__table__, [{"name": "MS Paint Adventures"}])
    op.add_column('search_character_groups', sa.Column('fandom_id', sa.Integer(), nullable=False, server_default="1"))
    op.create_foreign_key(None, 'search_character_groups', 'fandoms', ['fandom_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search_character_groups', type_='foreignkey')
    op.drop_column('search_character_groups', 'fandom_id')
    op.drop_table('fandoms')
    ### end Alembic commands ###
