"""Make secret question and answer nullable.

Revision ID: 18b4c8e0ab88
Revises: 1030718871ea
Create Date: 2015-10-10 20:08:40.431878

"""

# revision identifiers, used by Alembic.
revision = '18b4c8e0ab88'
down_revision = '1030718871ea'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'secret_answer',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('users', 'secret_question',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'secret_question',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'secret_answer',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    ### end Alembic commands ###
