"""quirk limits

Revision ID: 1b7d8bf0b4d8
Revises: 59c9813e6f67
Create Date: 2015-11-20 23:53:23.254696

"""

# revision identifiers, used by Alembic.
revision = '1b7d8bf0b4d8'
down_revision = '59c9813e6f67'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    tables = ['users', 'characters', 'search_characters', 'chat_users', 'requests']

    op.execute('COMMIT;')

    for table in tables:
        op.execute('ALTER TABLE %s ALTER COLUMN quirk_prefix TYPE character varying(2000);' % (table))
        op.execute('ALTER TABLE %s ALTER COLUMN quirk_suffix TYPE character varying(2000);' % (table))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
