"""Remove request search.

Revision ID: 1ddc1412be02
Revises: 145af6928bec
Create Date: 2016-03-29 21:45:35.865129

"""

# revision identifiers, used by Alembic.
revision = '1ddc1412be02'
down_revision = '145af6928bec'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_tags')
    op.drop_table('requests')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('requests_id_seq'::regclass)"), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'posted', name='requests_status'), autoincrement=False, nullable=False),
    sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('acronym', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('quirk_prefix', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('quirk_suffix', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('case', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('replacements', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('regexes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('scenario', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='requests_character_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='requests_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='requests_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('request_tags',
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name='request_tags_request_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='request_tags_tag_id_fkey'),
    sa.PrimaryKeyConstraint('request_id', 'tag_id', name='request_tags_pkey')
    )
    ### end Alembic commands ###
