"""Add age filter for character search.

Revision ID: 21c8e613be53
Revises: 6645b66bcce6
Create Date: 2017-06-09 23:35:44.712872

"""

# revision identifiers, used by Alembic.
revision = '21c8e613be53'
down_revision = '6645b66bcce6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('search_age_restriction', sa.Boolean(), nullable=False, server_default='false'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'search_age_restriction')
    ### end Alembic commands ###
