"""Add email verification field to users.

Revision ID: 231e2c1e26da
Revises: 35ed56b7b09
Create Date: 2016-05-28 23:06:18.316967

"""

# revision identifiers, used by Alembic.
revision = '231e2c1e26da'
down_revision = '35ed56b7b09'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    ### end Alembic commands ###
