"""New permission for resetting users' passwords.

Revision ID: 2325abc7de81
Revises: 18b4c8e0ab88
Create Date: 2015-10-12 22:49:41.867175

"""

# revision identifiers, used by Alembic.
revision = '2325abc7de81'
down_revision = '18b4c8e0ab88'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT;')
    op.execute('ALTER TYPE admin_tier_permissions_permission ADD VALUE \'reset_password\';')
    op.execute('INSERT INTO admin_tier_permissions (admin_tier_id, permission) VALUES (1, \'reset_password\');')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
