"""Add spam flag field to messages.

Revision ID: 2d7a23f85081
Revises: 8a47cc739e8
Create Date: 2015-06-28 18:55:45.374305

"""

# revision identifiers, used by Alembic.
revision = '2d7a23f85081'
down_revision = '8a47cc739e8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('spam_flag', sa.Unicode(length=15), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'spam_flag')
    ### end Alembic commands ###
