"""enable activity indicator

Revision ID: 30a41ccc3c3c
Revises: 8c6a92703ad
Create Date: 2016-02-22 00:58:00.556668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = '30a41ccc3c3c'
down_revision = '8c6a92703ad'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_users', sa.Column('enable_activity_indicator', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('enable_activity_indicator', sa.Boolean(), nullable=False, server_default='true'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'enable_activity_indicator')
    op.drop_column('chat_users', 'enable_activity_indicator')
    ### end Alembic commands ###
