"""Add chat_id to blocks.

Revision ID: 32615979a6ce
Revises: 2ac1e82fa9aa
Create Date: 2015-12-29 15:47:17.814345

"""

# revision identifiers, used by Alembic.
revision = '32615979a6ce'
down_revision = '2ac1e82fa9aa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blocks', 'chats', ['chat_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.drop_column('blocks', 'chat_id')
    ### end Alembic commands ###
