"""push tokens

Revision ID: 33f94a71e3a0
Revises: f8acbd22162
Create Date: 2016-01-30 18:43:29.818332

"""

# revision identifiers, used by Alembic.
revision = '33f94a71e3a0'
down_revision = 'f8acbd22162'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=4096), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_tokens')
    ### end Alembic commands ###
