"""Migration for the spam flags table.

Revision ID: 35ed56b7b09
Revises: 58c2374dc606
Create Date: 2016-05-01 22:41:01.113836

"""

# revision identifiers, used by Alembic.
revision = '35ed56b7b09'
down_revision = '58c2374dc606'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spam_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False, unique=True),
    sa.Column('type', ENUM(u'banned_names', u'blacklist', u'warnlist', name='spamless_filter_types', create_type=False), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('muted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spam_flags')
    ### end Alembic commands ###
