"""nsfwe matchmaking

Revision ID: 36db9588efa3
Revises: 1b7d8bf0b4d8
Create Date: 2015-11-21 00:10:27.872638

"""

# revision identifiers, used by Alembic.
revision = '36db9588efa3'
down_revision = '1b7d8bf0b4d8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.execute(u'COMMIT;')
    op.execute(u'ALTER TYPE user_search_level ADD VALUE \'nsfwe\';')


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
