"""Add draft column to chat_users.

Revision ID: 376e45cc835
Revises: 1fbbb727e1dc
Create Date: 2015-09-05 21:34:59.725852

"""

# revision identifiers, used by Alembic.
revision = '376e45cc835'
down_revision = '1fbbb727e1dc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_users', sa.Column('draft', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_users', 'draft')
    ### end Alembic commands ###
