"""Add theme column to chat users.

Revision ID: 40975dd21696
Revises: 43912ab8304e
Create Date: 2015-09-22 21:53:34.160708

"""

# revision identifiers, used by Alembic.
revision = '40975dd21696'
down_revision = '43912ab8304e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_users', sa.Column('theme', sa.Unicode(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_users', 'theme')
    ### end Alembic commands ###
