"""disable activity indicator

Revision ID: 4de8c51b9a23
Revises: 8c6a92703ad
Create Date: 2016-02-22 00:22:04.461946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = '4de8c51b9a23'
down_revision = '8c6a92703ad'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_users', sa.Column('disable_activity_indicator', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('disable_activity_indicator', sa.Boolean(), nullable=False, server_default='false'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disable_activity_indicator')
    op.drop_column('chat_users', 'disable_activity_indicator')
    ### end Alembic commands ###
