"""Remove unique constraint from SearchCharacter order.

Revision ID: 55eb2a993f60
Revises: 376e45cc835
Create Date: 2015-09-07 21:49:10.303840

"""

# revision identifiers, used by Alembic.
revision = '55eb2a993f60'
down_revision = '376e45cc835'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'search_character_groups_order_key', 'search_character_groups', type_='unique')
    op.drop_constraint(u'search_character_group_order_unique', 'search_characters', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'search_character_group_order_unique', 'search_characters', ['group_id', 'order'])
    op.create_unique_constraint(u'search_character_groups_order_key', 'search_character_groups', ['order'])
    ### end Alembic commands ###
