"""empty message

Revision ID: 59c9813e6f67
Revises: fa7e12c88c5
Create Date: 2015-11-03 22:20:51.669027

"""

# revision identifiers, used by Alembic.
revision = '59c9813e6f67'
down_revision = 'fa7e12c88c5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_users', sa.Column('show_timestamps', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('show_timestamps', sa.Boolean(), nullable=False, server_default='false'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'show_timestamps')
    op.drop_column('chat_users', 'show_timestamps')
    ### end Alembic commands ###
