"""Add date of birth to users.

Revision ID: 6645b66bcce6
Revises: a49bda99d39a
Create Date: 2017-06-01 23:30:59.685844

"""

# revision identifiers, used by Alembic.
revision = '6645b66bcce6'
down_revision = 'a49bda99d39a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_of_birth')
    ### end Alembic commands ###
