"""Add spamless message type.

Revision ID: 8a47cc739e8
Revises: 13bb58c7ab9b
Create Date: 2015-06-27 20:21:33.383686

"""

# revision identifiers, used by Alembic.
revision = '8a47cc739e8'
down_revision = '13bb58c7ab9b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute(u'COMMIT;')
    op.execute(u'ALTER TYPE messages_type ADD VALUE \'spamless\';')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
