"""Replace User.search_level with User.search_levels.

Revision ID: 8c6a92703ad
Revises: 2945717e3720
Create Date: 2016-02-04 22:09:48.619614

"""

# revision identifiers, used by Alembic.
revision = '8c6a92703ad'
down_revision = '2945717e3720'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('search_levels', postgresql.ARRAY(sa.Unicode(length=50)), nullable=False, server_default='{sfw}'))
    op.drop_column('users', 'search_level')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('search_level', postgresql.ENUM(u'sfw', u'nsfw', u'nsfwe', name='user_search_level'), autoincrement=False, nullable=False))
    op.drop_column('users', 'search_levels')
    ### end Alembic commands ###
