"""Split NSFW into NSFWS and NSFWV

Revision ID: a49bda99d39a
Revises: 09959133da91
Create Date: 2017-03-21 21:40:03.877236

"""

# revision identifiers, used by Alembic.
revision = "a49bda99d39a"
down_revision = "09959133da91"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT;")
    op.execute("ALTER TYPE group_chats_level ADD VALUE 'nsfws';")
    op.execute("ALTER TYPE group_chats_level ADD VALUE 'nsfwv';")
    op.execute("UPDATE group_chats SET level='nsfws' WHERE level='nsfw';")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
