"""Add new user group.

Revision ID: ea30a8851312
Revises: cac1f275a725
Create Date: 2016-12-13 23:10:06.709741

"""

# revision identifiers, used by Alembic.
revision = 'ea30a8851312'
down_revision = 'cac1f275a725'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT;")
    op.execute("ALTER TYPE users_group ADD VALUE 'new';")
    op.execute("ALTER TYPE users_group ADD VALUE 'deactivated';")
    op.execute("""UPDATE users SET "group"='deactivated' WHERE "group"='guest';""")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
