"""Initial

Revision ID: eddcb45d12
Revises: 
Create Date: 2015-05-17 12:29:32.567338

"""

# revision identifiers, used by Alembic.
revision = 'eddcb45d12'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
